/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCustomDialog.java
 *
 * Created on Jun 30, 2011, 11:51:39 PM
 */
package nubisave.ui;

import javax.swing.JOptionPane;
import nubisave.*;

/**
 *
 * @author demo
 */
public class AddCustomDialog extends javax.swing.JDialog {

    /** Creates new form AddCustomDialog */
    public AddCustomDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String showDialog() {
        setVisible(true);
        return cstmMntTextField.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cstmMntTextField = new javax.swing.JTextField();
        cstmMntAddBtn = new javax.swing.JButton();
        cstmMntCancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("custom mount command");

        cstmMntTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstmMntTextFieldActionPerformed(evt);
            }
        });

        cstmMntAddBtn.setText("Add");
        cstmMntAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstmMntAddBtnActionPerformed(evt);
            }
        });

        cstmMntCancelBtn.setText("Cancel");
        cstmMntCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstmMntCancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("%M% Mountpoint");

        jLabel3.setText("opt: %U% Username, %P% Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cstmMntTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addComponent(cstmMntCancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cstmMntAddBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cstmMntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cstmMntAddBtn)
                        .addComponent(cstmMntCancelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cstmMntAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstmMntAddBtnActionPerformed
        // no moint point given
        if (!cstmMntTextField.getText().contains("%M%")) {
            JOptionPane.showMessageDialog(this, "Please specify mount point", "no mount point", JOptionPane.ERROR_MESSAGE);
        } else {
            CustomMntPoint cstmMntPnt = new CustomMntPoint(cstmMntTextField.getText());
            cstmMntPnt.setMntCmd(cstmMntTextField.getText());
            Nubisave.services.getCstmMntPnts().add(cstmMntPnt);
            ((MainWindow) getParent()).tableModel.fireTableDataChanged();
            dispose();
        }
    }//GEN-LAST:event_cstmMntAddBtnActionPerformed

    private void cstmMntTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstmMntTextFieldActionPerformed
        cstmMntAddBtnActionPerformed(evt);
    }//GEN-LAST:event_cstmMntTextFieldActionPerformed

    private void cstmMntCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstmMntCancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cstmMntCancelBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cstmMntAddBtn;
    private javax.swing.JButton cstmMntCancelBtn;
    private javax.swing.JTextField cstmMntTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
