/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on May 24, 2011, 6:20:38 PM
 */
package nubisave.ui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.JFrame;
import javax.swing.JPanel;
import nubisave.component.graph.splitteradaption.NubisaveEditor;

/**
 *
 * @author demo
 */
public class MainWindow extends javax.swing.JFrame {
    //for tray icon
    private Image logo;
    private SystemTray sysTray;
    private PopupMenu menu;
    private MenuItem item_exit;
    private TrayIcon trayIcon;

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        //check to see if system tray is supported on OS.
        if (SystemTray.isSupported()) {
            setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            sysTray = SystemTray.getSystemTray();
            java.net.URL imageURL = this.getClass().getResource("/images/logo.png");
            logo  = Toolkit.getDefaultToolkit().getImage(imageURL);
            menu = new PopupMenu(); //tray icon popup menu
            item_exit = new MenuItem("Exit");
            menu.add(item_exit);
            item_exit.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   System.exit(0);
               }
            });
            trayIcon = new TrayIcon(logo, "Doubleclick to show. Right click to exit.", menu);
            trayIcon.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   setVisible(true);
               }
            });
            //add the tray icon to the system tray.
            try {
                sysTray.add(trayIcon);
            }
            catch(AWTException e) {
               System.out.println("System Tray unsupported!");
            }
        }
        NubisaveEditor editor = new NubisaveEditor();
        JPanel contentPane = new JPanel(new BorderLayout());
        contentPane.add(editor, BorderLayout.CENTER);
        setContentPane(contentPane);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NubiSave Cloud Storage Controller and Storage Flow Editor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1116, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables


}
