/*
 * MigrationDialog.java
 *
 * Created on 06.03.2012, 20:49:48
 */

package nubisave.ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import nubisave.Nubisave;
import nubisave.StorageService;

/**
 *
 * @author joe
 */
public class MigrationDialog extends javax.swing.JDialog {

    /** Creates new form MigrationDialog */
    public MigrationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        java.net.URL imageURL = this.getClass().getResource("/images/arrow_right.png");
        ImageIcon arrow = new ImageIcon(imageURL);
        moveDataBtn.setIcon(arrow);
        DefaultListModel sourceListModel = new DefaultListModel();
        DefaultListModel destinationListModel = new DefaultListModel();

        for(StorageService store: Nubisave.services){
            if(Nubisave.mainSplitter.isModuleMounted(store)){
                sourceListModel.addElement(store.getUniqName());
                destinationListModel.addElement(store.getUniqName());
            }
        }
        sourceStoreList.setModel(sourceListModel);
        sourceStoreList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        destinationStoreList.setModel(destinationListModel);
        destinationStoreList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jProgressBar1 = new javax.swing.JProgressBar();
        moveDataBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        destinationStoreList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        sourceStoreList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        moveDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDataBtnActionPerformed(evt);
            }
        });

        destinationStoreList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(destinationStoreList);

        sourceStoreList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(sourceStoreList);

        jLabel1.setText("Move Data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(moveDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDataBtnActionPerformed
        int sourceSelectedIndex = sourceStoreList.getSelectedIndex();
        int destinationSelectedIndex = destinationStoreList.getSelectedIndex();
        if(sourceSelectedIndex == -1 || destinationSelectedIndex == -1){
            return;
        }
        String sourceStore = (String) sourceStoreList.getModel().getElementAt(sourceSelectedIndex);
        String destinationStore = (String) sourceStoreList.getModel().getElementAt(destinationSelectedIndex);
        Nubisave.mainSplitter.moveStoreData(sourceStore, destinationStore);
    }//GEN-LAST:event_moveDataBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList destinationStoreList;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton moveDataBtn;
    private javax.swing.JList sourceStoreList;
    // End of variables declaration//GEN-END:variables

}
