#!/bin/bash
#
# Informs about the status of Nubisave instances

storagesdir=~/.storages

nubilist=`ls $storagesdir/Nubisave* 2>/dev/null`
if [ -z $nubilist ]
then
	echo "! No NubiSave instances configured."
fi
for nubi in $nubilist
do
	echo "- NubiSave configured at: $nubi"
done

mnts=`mount | grep nubisave | awk '{print $3}'`
if [ -z $mnts ]
then
	echo "! No NubiSave instances mounted."
fi
for mnt in $mnts
do
	echo "- NubiSave mounted at: $mnt"
	df=`/bin/df | grep "$mnt" | cut -d " " -f 1`
	if [ $df ]
	then
		echo "  * with mounted storages"

		ifs=IFS
		IFS="
"
		for line in `cat $storagesdir/connections.txt`; do
			nubi=`echo $line | cut -d " " -f 1`
			storage=`echo $line | cut -d " " -f 2`
			x=" "
			# TODO: This should be equivalent with -f nubisavemount/config/$storage
			if [ -d $storagesdir/$storage ]; then
				x="x"
			fi
			echo "    [$x] $storage"
		done
		IFS=$ifs
	else
		echo "  * without mounted storages"
	fi
done
