#!/bin/sh
#
# Mounts all configured Nubisave directories
# Useful for headless configurations

storagesdir=~/.storages
configdir=~/.nubisave/db/splitter_configuration
splitterdir=/usr/share/nubisave/splitter/

if [ ! -d $configdir ]
then
	echo "Error: Configuration directory $configdir does not exist." >&2
	exit 1
fi

cd $configdir
if [ -z "`ls`" ]
then
	echo "No storage modules configured, not mounting anything."
	exit 0
fi

for storage in *
do
	echo "Storage: $storage"
	mount=`grep ^mountcommand $storage | cut -d "=" -f 2-`
	for param in $mount
	do
		#echo "--param:$param"
		paramval=`grep ^$param $storage`
		if [ $? = 0 ]
		then
			paramval=`echo $paramval | cut -d "=" -f 2-`
			#echo "**$paramval"
			mount=`echo $mount | sed -e "s& $param& $paramval&"`
		fi
	done

	mountpoint=$storagesdir/$storage
	mount=`echo $mount | sed -e "s& mountpoint& $mountpoint&"`
	echo "* mount: $mount"

	# Hot-plugging for indirect mounting through Nubisave
	cp $storage ~/.nubisave/nubisavemount/config

	# Deprecated: Manual mounting
	#mkdir -p $mountpoint $mountpoint/config
	#cd $splitterdir
	#$mount
	#cd $configdir
done
