#!/bin/sh

if [ ! -d debian ]; then
	echo "Error: Needs to be called from top-level directory as ./debian/rebuild" >&2
	exit 1
fi

if [ "$1" = "--prep" ]; then
	apt-get install devscripts dh-make
	apt-get install openjdk-6-jdk python-setuptools libfuse-dev
	exit 0
fi

which debuild >/dev/null && which dh_make >/dev/null
if [ $? != 0 ]; then
	echo "Error: Needs build tools and dependencies. Call script with --prep first."
	exit 1
fi

if [ ! -d CloudFusion ]; then
	# git submodule init
	# git submodule update CloudFusion
	git clone git://github.com/joe42/CloudFusion.git
fi

if [ "$1" = "--force" ]; then
	rm -f ../nubisave_*
	git clean -df
fi

stamp=`date +%Y%m%d`

rm -rf debian/nubisave
echo y | dh_make -i --createorig -p nubisave_0.0~git$stamp
if [ ! -f ../*.orig.tar.gz ]; then
	# Workaround for old squeezy dh_make
	origdir=$PWD
	cd ../*.orig
	tarname=`basename $PWD`
	tarname=`echo $tarname | sed -e 's/-/_/'`.tar.gz
	tar cfz ../$tarname .
	cd $origdir
fi
debuild

make -f debian/rules clean
